hnz.cpp, hnzconf.cpp, hnzconnection.cpp, include/hnz.h, include/hnzconf.h, include/hnzconnection.h
#2 Re-implementation of the HNZ logic (EDF HNZ S13):
- Establishing the connection (SARM, UA)
- Sending and receiving acknowledgements (RR)
- Sending information frames (with good numbering management - NS/NR/P/F fields in 2nd byte)
- Sending time and date setting messages
=> 2 connection management

.github/workflows/ci.yml, CMakeLists.txt, cmake/CodeCoverage.cmake, include/hnzpath.h, tests/CMakeLists.txt
=> Updated CMakeLists.txt to handle gcov code coverage on unit tests.

src/hnzpath.cpp, tests/server/basic_hnz_server.cpp, tests/server/basic_hnz_server.h, tests/test_hnz.cpp
=> refs #29 Fixed TC frame generation

.github/workflows/ci.yml, include/hnzconf.h, include/hnzpath.h, src/hnzconf.cpp, src/hnzpath.cpp, tests/test_hnzconf.cpp
=> Fix massive cpu usage when plugin connected to pa

include/hnz.h, include/hnzpath.h, src/hnz.cpp, src/hnzpath.cpp, tests/test_hnz.cpp
=> Removed code related to val_coding in TVC messages handling.

CMakeLists.txt, include/hnz.h, include/hnzpath.h, src/hnz.cpp, src/hnzpath.cpp, tests/server/basic_hnz_server.cpp, tests/server/basic_hnz_server.h, tests/test_hnz.cpp
=> Store validity of TC/TVC ack in reading

include/hnz.h, include/hnzconf.h, include/hnzconnection.h, src/hnz.cpp, src/hnzconf.cpp, src/hnzconnection.cpp, src/plugin.cpp, tests/test_hnz.cpp, tests/test_hnzconf.cpp
=> Replaced data_object types "TSCE" and "TSCG" by "TS" and added optional "do_cg" field.

src/hnz.cpp, tests/test_hnz.cpp
=> Replaced data_object types "ACK_TC" by "TC" and "ACK_TVC"  by "TVC"

include/hnz.h, src/hnz.cpp, src/plugin.cpp, tests/test_hnz.cpp, tests/test_hnzconf.cpp
=> Replaced data_object types "TMA" and "TMN" by "TM" and added optional "do_an" field.

include/hnzconf.h, src/hnzconf.cpp, src/plugin.cpp, tests/test_hnz.cpp, tests/test_hnzconf.cpp, tests/test_hnzconnection.cpp, tests/test_plugin.cpp
=> Updated exchanged_data fields to match the structure provided by PowerConf.

include/hnz.h, include/hnzconf.h, include/hnzconnection.h, include/hnzpath.h, src/hnz.cpp, src/hnzconf.cpp, src/hnzconnection.cpp, src/hnzpath.cpp, src/plugin.cpp, tests/server/basic_hnz_server.cpp, tests/test_hnz.cpp, tests/test_hnzconf.cpp, tests/test_hnzconnection.cpp
=> Added connection loss status and GI status management.

include/hnz.h, include/hnzconf.h, include/hnzconnection.h, include/hnzpath.h, src/hnz.cpp, src/hnzconf.cpp, src/hnzconnection.cpp, src/hnzpath.cpp, tests/test_hnz.cpp, tests/test_hnzconf.cpp
=> Added early finish for CG requests when the last expected TS is received.

include/hnz.h, include/hnzconf.h, include/hnzconnection.h, src/hnz.cpp, src/hnzconnection.cpp, tests/test_hnz.cpp, tests/test_hnzconf.cpp
=> Added quality update readings.

include/hnz.h, src/hnz.cpp, src/hnzconf.cpp, src/hnzpath.cpp, tests/test_hnz.cpp, tests/test_plugin.cpp
=> 73 new command object structure

.github/workflows/ci.yml
=> refs #79 Update sonar scanner version for CI.

.github/workflows/ci.yml, tests/server/basic_hnz_server.cpp, tests/server/basic_hnz_server.h, tests/test_hnz.cpp
This change must be merged first in order to have a CI running normally on https://github.com/fledge-power/fledge-south-hnz/pull/92
=> refs #PMP2-244 Added missing include dependency for unit test build.

include/hnz.h, include/hnzconnection.h, include/hnzpath.h, include/hnzutility.h, src/hnz.cpp, src/hnzconnection.cpp, src/hnzpath.cpp, src/plugin.cpp, tests/test_utility.cpp
=> PMP2-244 add connection status audit messages

src/hnzpath.cpp, tests/test_hnz.cpp
Reject frames with invalid direction bit (A/B) as specified by HNZ documentation + unit test covering the modification.
=> refs #PMP2-304 Validation of HNZ frames direction bit (A/B)

include/hnz.h, include/hnzconnection.h, include/hnzpath.h, src/hnz.cpp, src/hnzconnection.cpp, src/hnzpath.cpp, tests/server/basic_hnz_server.cpp, tests/server/basic_hnz_server.h, tests/test_hnz.cpp
Updating the HNZ connection automaton to better fit the specifications of HNZ protocol.
=> refs #PMP2-277 New HNZ automaton

include/hnz.h, include/hnzconf.h, src/hnz.cpp, src/hnzconf.cpp, tests/test_hnz.cpp, tests/test_hnzconf.cpp
Should be merged before https://github.com/fledge-power/fledge-south-hnz/pull/110
=> refs #PMP2-378 GI on EXP.PART
